### ISSUE TITLE
Solution for choosing the AHF version on Mac OS X without using environment variables?

### ISSUE THREAD

**Issue by tofi86** [AntennaHouse/Alternate-XfoJavaCtl#3]
Hi @brugal,

this is a reply to [AH #12840] but my email was recognized as spam :-( So here we go in GitHub then...

Calling `XfoObj("AHF62_HOME")` won't pick up the 6.2 version but instead the 6.3 version.
Okay, get it. There's a javadoc comment for "public XfoObj (String preferredHome)" which reads as follows:

> This is specified as a Formatter home environment variable (ex: AHF63_HOME, AHF62_64_HOME, etc.) and needs to already be defined in the user's environment.

While I understand that for Windows (where setting the PATH/ENVIRONMENT variables is an installer option) I don't understand it for Mac OS X.
Normally on Mac OS X there's never AHF env variables set, right?
We also didn't alter the `DYLD_LIBRARY_PATH` when installing AHF 6.2...

So is there an option to specify which version to use on Mac OS X without having to set environment variables first?

How is Antenna House Formatter determining which version to use when there's no environment variables set on Mac OS X?
Does it scan the `/usr/local/` directory for `AHFormatterV\d\d` entries and picking the first?
It seems this isn't part of the `Alternate-XfoJavaCtl` at the moment but of the Formatter binary...

Could it be a solution to just provide the path the the formatter executable when calling `new XfoObj()` or `render()` in the form `/usr/local/AHFormatterV62/bin/AHFCmd`?

Regards,
Tobias

/cc @christin-goetz

**Comment by brugal** [comment]
Hello Tobias,

That's correct, the Unix versions of Formatter (Linux, Mac OS X, etc..) don't set any environment variables (AHF_*, PATH, or [DY]LD_LIBRARY_PATH).  The Java library that ships with Formatter makes native calls and is designed to only work with that particular version so you would need to set the appropriate environment variables depending on that version of the library.  Switching between 6.2 and 6.3 would also require changing the reference to XfoJavaCtl.jar in your project since the library between two versions aren't compatible.  Formatter doesn't do any scanning for versions and instead references the specific environment variables that correspond to it (ex: 6.3mr2 is hard coded to use AHF63_[64_]HOME).

With the Alternate interface Formatter is used as an external process so it's not tied to one specific version of Formatter.  That's why it needs to scan the variables to know which version to use.

I'll see if I can add another method of specifying a location for the Formatter installation.  That would also set up the appropriate environment variables as well.

**Comment by brugal** [comment]
https://github.com/AntennaHouse/Alternate-XfoJavaCtl/commit/164e5f86e1bfb7fa6ccd855cdffc4272c0d38ddb

Added an additional optional parameter for the constructor:

  XfoObj(String preferredHome, String specifiedFormatterInstallation)

'specifiedFormatterInstallation' should be an absolute path to a Formatter installation.  'preferredHome' still needs to be set (AHF61_64_HOME, etc..) so that the version in the specified path is known and the appropriate environment variables can be set automatically.  This doesn't require any environment variables to be set from the calling environment.  Let me know if you run into any problems with the changes.

**Comment by tofi86** [comment]
Hi Angelo, sorry for the late reply, but vacation came across :smirk:

Unfortunately I can't get it to work on Mac OS X. :disappointed:
I mean, I probably could, but then I would need to build the `preferredHome` value (`AHF63_HOME`, etc..) from the provided path (`specifiedFormatterInstallation`). But that's exactly what you're doing later on in the `XfoObj` constructor. In this case we would do it twice and the method `checkForLatestUnixFormatterDirectory` should be public so I could use it in the first hand. It doesn't make very much sense to me...

Would `XfoObj(String specifiedFormatterInstallation)` be so hard to implement? After scanning the `specifiedFormatterInstallation` path you would be able to create the `preferredHome` variable by yourself – I mean you're already doing it in `checkForLatestUnixFormatterDirectory` in line 228 ff

What do you think?

P.S.: `XfoObj(null, '/usr/local/AHFormatterV62')` does not work because it's failing in line 277

**Comment by brugal** [comment]
Hello Tobias,

You don't have to prepare the value of the AHF*_HOME variable just its name:

  XfoObj("AHF62_HOME", "/usr/local/AHFormatterV62");

That will then automatically create all the other necessary AHF\* variables (AHF62_LIC_PATH, LD_LIBRARY_PATH, etc...).

The first parameter is needed since it might not be possible to determine the Formatter version from just the path name in the second parameter.  Ex:  XfoObj(null, "/share/formatter")

**Comment by tofi86** [comment]
Hi Angelo,

okay, I understand, but then I need to parse the provided path to generate the AHF*_HOME variable (the name!).

Our customers need to provide the path to the AH install directory in a config file. That's the only thing I have to work with.
So to construct either `XfoObj("AHF62_HOME")` or `XfoObj("AHF62_HOME", "/usr/local/AHFormatterV62")` I'm missing the `"AHF62_HOME"` part.

So I also have to parse the provided path in order to find some numerics which I can use to construct the `AHF*_HOME` key.

> But that's exactly what you're doing later on in the `XfoObj` constructor. In this case we would do it twice and the method `checkForLatestUnixFormatterDirectory` should be public so I could use it in the first hand.

That's what I meant in my comment above...

**Comment by brugal** [comment]
Hello Tobias,

This commit (https://github.com/AntennaHouse/Alternate-XfoJavaCtl/commit/48452f695731a32c08cbd3f6a8ef95ebe607002a) adds support for the first parameter to be null with Unix versions.  If it's null then the specified directory name will be parsed to try and get the Formatter version.  Ex:  XfoObj(null, "/test/AHFormatterV63").  Note that the top directory needs to be in the same format as the default name used with Formatter installs (ex:  AHFormaterV*).

**Comment by tofi86** [comment]
Hi Angelo,

thanks for the additional code changes. However, there were still problems and when passing `/usr/local/AHFormatterV62` it would take the 6.3 version anyways.

I sent a pull request #4 with a fix and this works very well for me.

Thanks!
